# Generated by Django 5.1.3 on 2026-02-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_willie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookiecategory",
            name="slug",
            field=models.SlugField(
                help_text="Unique identifier for this category (e.g., 'analytics', 'marketing')",
                max_length=100,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cookiecategory",
            unique_together={("translation_key", "locale")},
        ),
    ]
